version: "3.3"

services:
  db:
    image: postgres:12.11
    restart: always
    environment:
      POSTGRES_USER: moshaere
      POSTGRES_DB: moshaere
      POSTGRES_PASSWORD: moshaere
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data/poems.sql:/docker-entrypoint-initdb.d/poems.sql
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  db_data:
  redis_data:
